### ISSUE TITLE
breaks npm v3.3.5/3.3.6 outdated cmd when listed as a devDependency in package.json

### ISSUE THREAD

**Issue by mshick** [tjmehta/101#113]
Pretty crazy issue. My `npm outdated` started failing... After some tracing I noticed that `101` causes a weird run in the dependency array built in the npm `outdated` utility. I'm guessing this is a npm bug related to the numeric module name (tests with "202" and "2" showed the same result).

Documenting here, in case you want to raise an issue with the npm team. A brief search makes me think this hasn't been filed yet.

Steps to reproduce:

* add any module with a numeric name to the `devDependencies` object in package.json
* run `npm outdated`
* receive error like below

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/Users/mshick/.node/bin/npm" "outdated"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'name' of undefined
```

Here's a sample npm-debug.log entry:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.1/bin/node',
1 verbose cli   '/Users/mshick/.node/bin/npm',
1 verbose cli   'outdated' ]
2 info using npm@3.3.6
3 info using node@v4.2.1
4 silly mapToRegistry name MD5
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/MD5
8 silly mapToRegistry name adm-zip
9 silly mapToRegistry using default registry
10 silly mapToRegistry registry https://registry.npmjs.org/
11 silly mapToRegistry uri https://registry.npmjs.org/adm-zip
12 verbose stack TypeError: Cannot read property 'name' of undefined
12 verbose stack     at /Users/mshick/.node/lib/node_modules/npm/lib/outdated.js:295:27
12 verbose stack     at /Users/mshick/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
12 verbose stack     at Array.forEach (native)
12 verbose stack     at /Users/mshick/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
12 verbose stack     at Array.forEach (native)
12 verbose stack     at asyncMap (/Users/mshick/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
12 verbose stack     at outdated_ (/Users/mshick/.node/lib/node_modules/npm/lib/outdated.js:294:3)
12 verbose stack     at /Users/mshick/.node/lib/node_modules/npm/lib/outdated.js:78:5
12 verbose stack     at /Users/mshick/.node/lib/node_modules/npm/lib/install/deps.js:119:5
12 verbose stack     at LOOP (/Users/mshick/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
13 verbose cwd /Users/mshick/code/project
14 error Darwin 15.0.0
15 error argv "/usr/local/Cellar/node/4.2.1/bin/node" "/Users/mshick/.node/bin/npm" "outdated"
16 error node v4.2.1
17 error npm  v3.3.6
18 error Cannot read property 'name' of undefined
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ 1, true ]
```

**Comment by tjmehta** [comment]
Interesting, will check it out and followup with npm tonight.

Thanks!

**Comment by mshick** [comment]
@tjmehta any word? Curious if you have the same results...

**Comment by bkendall** [comment]
I confirmed this this morning. Looks like it was possibly introduced with `npm@3.0.0`

```bash
» npm outdated # npm v2.14.8
Package  Current  Wanted  Latest  Location
101        0.9.0   0.9.0   1.2.0  101
```

```bash
» npm outdated # nvm v3.0.0
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/bkendall/.nvm/versions/node/v4.2.1/bin/node" "/Users/bkendall/.nvm/versions/node/v4.2.1/bin/npm" "outdated"
npm ERR! node v4.2.1
npm ERR! npm  v3.0.0

npm ERR! Cannot read property 'name' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bkendall/Repositories/docker-mock/npm-debug.log
```

```bash
» npm outdated # npm v3.3.8
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/bkendall/.nvm/versions/node/v4.2.1/bin/node" "/Users/bkendall/.nvm/versions/node/v4.2.1/bin/npm" "outdated"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at moduleName (/Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/utils/module-name.js:25:3)
npm ERR! typeerror     at /Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/outdated.js:296:16
npm ERR! typeerror     at /Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at outdated_ (/Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/outdated.js:295:3)
npm ERR! typeerror     at /Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/outdated.js:79:5
npm ERR! typeerror     at /Users/bkendall/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/install/deps.js:121:5
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bkendall/Repositories/docker-mock/npm-debug.log
```

A [gist of the npm@3.3.8](https://gist.github.com/bkendall/367687dca1e4d64f7705) is available

**Comment by mshick** [comment]
@bkendall thanks for the confirmation.

I'll open an issue at npm.

**Comment by tjmehta** [comment]
@mshick sorry for the delay, thanks for the hand @bkendall
